name: Docker Image CI
on:
  push:
    branches: [ "producao", "homologacao" ]
  pull_request:
    branches: [ "producao", "homologacao" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Faz o build da imagem para ambiente de homologacao
    - name: Build imagem docker Homologacao
      if: github.ref == 'refs/heads/homologacao'
      run: docker build . --build-arg AMBIENTE=staging -t devroboflex/thalamus-avaliacao-desempenho-frontend:hml

    - name: Push imagem docker homologacao
      if: github.ref == 'refs/heads/homologacao'
      run: docker push devroboflex/thalamus-avaliacao-desempenho-frontend:hml

    # Faz o build da imagem para o ambiente de producao
    - name: Build imagem docker Produção
      if: github.ref == 'refs/heads/producao'
      run: docker build . --build-arg AMBIENTE=production -t devroboflex/thalamus-avaliacao-desempenho-frontend:latest

    - name: Push imagem docker Producao
      if: github.ref == 'refs/heads/producao'
      run: docker push devroboflex/thalamus-avaliacao-desempenho-frontend:latest
